### ISSUE TITLE
Can't create DHL shipping label

### ISSUE THREAD

**Issue by tanolalano** [amzn/amazon-pay-magento-2-alexa-plugin#3]
Hi all,
I can't create DHL shipping label if the plugin is Active. No error found in shipment log or in magento error.log.
If I insert  the tracking code to create shipment I get error http 500 
I found in the apache log the error related  

`[Tue Jan 07 10:03:35.201427 2020] [proxy_fcgi:error] [pid 11096:tid 140097168914176] [client 127.0.0.1:60830] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'AmazonPayV2\\Client' not found in vendor/amzn/amazon-pay-magento-2-alexa-plugin/Model/Alexa.php:200\nStack trace:\n#0 vendor/amzn/amazon-pay-magento-2-alexa-plugin/Model/Alexa.php(115): Amazon\\Alexa\\Model\\Alexa->submitDeliveryTracker('P02-6431880-916...', '5410176730', 'dhl', 'DHL')\n#1 /opt/bitnami/apps/magento/htdocs/vendor/amzn/amazon-pay-magento-2-alexa-plugin/Observer/SalesOrderShipmentTrackAfter.php(67): Amazon\\Alexa\\Model\\Alexa->addDeliveryNotification(Object(Magento\\Sales\\Model\\Order\\Shipment\\Track))\n#2 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Amazon\\Alexa\\Observer\\SalesOrderShipmentTrackAfter->execute(Object(Magento\\Framework\\Event\\Observer))\n#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Amazon\\Alexa\\Ob...\n', referer: https://mysite.com/admin/order_shipment/new/order_id/7838/key/d6978ea81364e7b9c79364a80f015e60e839dfaf83a9fb508c154e3547d64a2d/`

**Comment by christianzichichi** [comment]
Hi @tanolalano, thanks for contacting us.

From the error above, it seems to me as if the Amazon Pay V2 SDK for PHP hasn’t been installed correctly after a manual installation of the Alexa Module. Can you check if the composer part of the installation procedure is executed successfully? In particular:

`composer require amzn/amazon-pay-sdk-v2-php`
 
Afterwards, there should be a directory `amazon-pay-sdk-v2-php` inside the `vendor/amzn` directory of your Magento 2 installation.

Thanks
Regards

Christian
